# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Site Title
email: my-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write a description for this in _config.yml for head > meta 
  and feed.xml site descript.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.alexadelle.com" # the base hostname & protocol for your site
twitter_username: kreauchee
github_username:  kreauchee

# Build settings
markdown: kramdown
